blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from portfolio import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateField()
    description = models.TextField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def all_blogs(request):
    blogs = Blog.objects.order_by('-date')                                       # импорт всех записей из базы данных и сортировка по дате "order_by('-date')"
    return render(request, 'blog/all_blogs.html', {'blogs': blogs})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    projects = Project.objects.all()                                        # импорт всех записей из базы данных
    return render(request, 'portfolio/home.html', {'projects': projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}


  <h1 id="blogtitle" class="font-weight-bold text-center">Блог</h1>

  <h2 class="text-center mb-5">Всего постов: {{ blogs.count }}</h2>

  {% for blog in blogs %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
    <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
    <p>{{ blog.description|safe|truncatechars:100 }}</p>
  </div>
</div>

  {% endfor %}


{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}


    <h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>

    <h2 class="text-center text-muted mb-5">--{{ blog.date|date:'M d Y' }}--</h2>

    {{ blog.description|safe }}


{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans&family=Open+Sans&family=Overpass&display=swap" rel="stylesheet">

    <link rel="icon" type="image/png" href="{% static "portfolio/для логотипаыыы.png" %}">

    <title>Михаил Головешкин</title>
  </head>

  <body>

    <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "portfolio/для логотипаыыы.png" %}" height="30" class="d-inline-block align-top" alt="Meshik Logo">
        <span>Михаил Головешкин</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar navbar-light bg-light" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li>
            <a role="button" href="#" class="btn btn-outline-success me-2" target="_blank">Резюме</a>
          </li>
          <li>
            <a role="button" href="https://www.youtube.com/channel/UCgDIQs1e97MHaNRNY-8Yk4Q" class="btn btn-outline-danger me-2" target="_blank">Мой YouTube</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-outline-primary me-2">Блог</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">

{% block content %}{% endblock %}

  </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>

</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}

{% load static %}

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Этот сайт - мой второй учебный проект на Django на пути становления разработчиком</h1>
  </div>
</div>

<div class="row justify-content-center my-3">
  <div class="col-md-9 text-center">
    <img src="{% static 'portfolio/ZEPETO_-8585691018672160088.png' %}">
  </div>
</div>

<h2 class="mt-5">Мои Видео</h2>

<hr>

<div class="row">
    {% for project in projects %}
    <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}" target="_blank">
        <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>

    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">

    {% endif %}

    <h2>{{ project.title }}</h2>
    <p>{{ project.description }}</p>

    </div>
    {% endfor %}
</div>

{% endblock %}